version: '3.9'

services:
  rairnode:
    container_name: 'rairnode'
    build:
      context: demo-decrypt-node/
      dockerfile: Dockerfile
    volumes:
      - ./demo-decrypt-node/db:/usr/local/src/db
      - ./demo-decrypt-node/bin/Videos:/usr/local/src/bin/Videos
    environment:
      PRODUCTION: "false"
      MONGO_URI: mongodb+srv://${dbuser}:${dbpass}@${dbhost}
      MONGO_URI_LOCAL: mongodb://${localdbuser}:${localdbpass}@mongo:27017/rair-db?authSource=${localdbuser}
      PINATA_SECRET: ${pinata_secret}  
    ports:
      - 3000:3000
      - 5000:5000
    networks:
      - rair-local
  rairfront:
    container_name: 'rairfront'
    build:
      context: rair-front-master/
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - rair-local
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./demo-decrypt-node/dev/db-data:/data/db
      - ./demo-decrypt-node/dev/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${localdbuser}
      MONGO_INITDB_ROOT_PASSWORD: ${localdbpass}
      MONGO_INITDB_DATABASE: rair-db
    ports:
      - 27017:27017
    networks:
      - rair-local
  minting-network:
    container_name: minting-network
    expose: 
      - "80"
    build:
      context: blockchain-demos/frontend-minting-marketplace
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - rair-local
networks:
  rair-local:
    driver: bridge
