version: '3.9'

services:
  rairnode:
    container_name: 'rairnode'
    image: rairtechinc/rairservernode:dev_latest
    volumes:
      - ./demo-decrypt-node/db:/usr/local/src/db
      - ./demo-decrypt-node/bin/Videos:/usr/local/src/bin/Videos
    ports:
      - 3000:3000
      - 5000:5000
    networks:
      - rair-local
  rairfront:
    container_name: 'rairfront'
    image: rairtechinc/rairfront:dev_latest
    ports:
      - 80:80
    networks:
      - rair-local

  minting-network:
    container_name: minting-network
    image: rairtechinc/minting-network:dev_latest
    ports:
      - 3001:3001
    networks:
      - rair-local
networks:
  rair-local:
    driver: bridge
