version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: rair-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
    #  - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    environment:
      - ENV=development
      - APPLICATION_URL=http://minter-network
    networks:
      - rair-local
    depends_on:
      - minting-network

  rairnode:
    container_name: 'rairnode'
    image: rairtechinc/rairservernode:dev_latest
    volumes:
      - ./demo-decrypt-node/db:/usr/local/src/db
      - ./demo-decrypt-node/bin/Videos:/usr/local/src/bin/Videos
    environment:
      PRODUCTION: "true"
      MONGO_URI: mongodb+srv://${dbuser}:${dbpass}@${dbhost}
      MONGO_URI_LOCAL: mongodb://${localdbuser}:${localdbpass}@mongo:27017/rair-db?authSource=${localdbuser}
      JWT_SECRET: ${jwt_secret}
      PINATA_SECRET: ${pinata_secret}
      ADMIN_NETWORK: ${admin_nft_chain}
      ADMIN_CONTRACT: ${admin_contract}
      INFURA_PROJECT_ID: ${infura_project_id}
      SERVICE_HOST: ${hostname}
    ports:
      - 3000:3000
      - 5000:5000
    networks:
      - rair-local
  rairfront:
    container_name: 'rairfront'
    image: rairtechinc/rairfront:dev_latest
    ports:
      - 8080:80
    networks:
      - rair-local

  minting-network:
    container_name: minting-network
    image: rairtechinc/minting-network:dev_latest
    expose:
      - "80"
    ports:
      - 3001:3001
    networks:
      - rair-local
networks:
  rair-local:
    driver: bridge
