apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    dockerfile: version
  creationTimestamp: null
  labels:
    io.kompose.service: blockchain-event-listener
  name: blockchain-event-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blockchain-event-listener
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/rair-local: "true"
        io.kompose.service: blockchain-event-listener
    spec:
      containers:
        - image: rairtechinc/blockchain-event-listener:dev_latest
          name: rairnode
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credential
                  key: MONGO_URI
            - name: PINATA_SECRET
              valueFrom:
                secretKeyRef:
                  name: pinata-secret
                  key: PINATA_SECRET
          envFrom:
          - configMapRef:
              name: blockchain-event-listener-env
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
