apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: rairnode
  name: rairnode
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rairnode
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/rair-local: "true"
        io.kompose.service: rairnode
    spec:
      containers:
        - image: rairtechinc/rairservernode:dev_latest
          name: rairnode
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 5000
          env:
            - name: PRODUCTION
              value: "true"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credential
                  key: MONGO_URI
            - name: MONGO_URI_LOCAL
              value: "mongodb://admin:admin@mongo:27017/rair-db?authSource=admin"
            - name: INFURA_PROJECT_ID
              value: "92a88973a28d41318792f77451db4c5b"
            - name: ADMIN_NETWORK
              value: "matic"
            - name: ADMIN_CONTRACT
              value: "0xe5a9efb29b82517166fcef23722452543b5f380f"
            - name: SERVICE_HOST
              value: "dev.rair.tech"
            - name: PINATA_SECRET
              value: "92a0712843d62a70a2cad282bb7369b42be4ddd288543cc861a792d91d3c10a1"
            - name: sentry_enabled
              value: "true"
            - name: sentry_endpoint
              value: "https://b1b9b63c8d484d35a7f47235c681201b@o1004167.ingest.sentry.io/5965143"
            - name: sentry_trace_rate
              value: "1.0"
            - name: sentry_release
              value: "unknown_development_build"
            - name: default_product_cover
              value: "https://rair.mypinata.cloud/ipfs/QmNtfjBAPYEFxXiHmY5kcPh9huzkwquHBcn9ZJHGe7hfaW"
            - name: matic_testnet_rpc
              value: "https://polygon-mumbai.infura.io/v3/92a88973a28d41318792f77451db4c5b"
            - name: matic_mainnet_rpc
              value: "https://polygon-mainnet.infura.io/v3/92a88973a28d41318792f77451db4c5b"
            - name: ethereum_mainnet_rpc
              value: "https://mainnet.infura.io/v3/92a88973a28d41318792f77451db4c5b"
            - name: ethereum_testnet_goerli_rpc
              value: "https://goerli.infura.io/v3/92a88973a28d41318792f77451db4c5b"
            - name: binance_testnet_rpc
              value: "https://data-seed-prebsc-1-s1.binance.org:8545/"
            - name: binance_mainnet_rpc
              value: "https://bsc-dataseed.binance.org/"
            - name: JWT_SECRET
              value: "UGt70v4#mZ0J@vHFK%b"
            - name: GCP_PROJECT_ID
              value: "rair-market"
            - name: GCP_IMAGE_BUCKET_NAME
              value: "rair_images"
            - name: GCP_VIDEO_BUCKET_NAME
              value: "rair-videos"
            - name: GCP_GATEWAY
              value: "https://storage.googleapis.com"
            - name: GCP_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: rair-manager-key
                  key: key.json
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/src/db
              name: rairnode-claim0
            - mountPath: /usr/local/src/bin/Videos
              name: rairnode-claim1
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: rairnode-claim0
          persistentVolumeClaim:
            claimName: rairnode-claim0
        - name: rairnode-claim1
          persistentVolumeClaim:
            claimName: rairnode-claim1
status: {}
