apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rair
  creationTimestamp: null
  labels:
    io.kompose.service: rairnode-claim0
  name: rairnode-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
